### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by QPLAYid** [MikaCybertron/PMT-Dumper#1]
![Screenshot_2023-02-24-05-40-17-969-edit_com radinc csharpshell](https://user-images.githubusercontent.com/102419809/221025223-a010a11d-408b-428f-80d3-c7f792a023bf.jpg)

I try fix elf and no i get same error

**Comment by MikaCybertron** [comment]
nah SoFixer just can fix some segment and relocation of elf files, if the elf files fully encrypted then SoFixer can not fix the file. 

so i suggest you to use Zygisk Il2CppDumper for that
link: https://github.com/Perfare/Zygisk-Il2CppDumper

**Comment by QPLAYid** [comment]
> nah SoFixer just can fix some segment and relocation of elf files, if the elf files fully encrypted then SoFixer can not fix the file.
> 
> so i suggest you to use Zygisk Il2CppDumper for that link: https://github.com/Perfare/Zygisk-Il2CppDumper

You app not support virtual app ? 
I want dump wit virtual app but you app crash 
Can fix it ?

**Comment by MikaCybertron** [comment]
> You app not support virtual app ?
> I want dump wit virtual app but you app crash
> Can fix it ?

it is because the code of PMT Dumper not for virtual app, but it can be used in Virtual Machine like VMOS, VPhoneGaga, x86 Sandbox and F1 VM
